name: lcc env
description: Simple action to build and tests e2k code. This action install lcc crosscompiler and qemu-e2k-static emulator.
author: mrognor
inputs:
  lcc_link:
    required: false
    description: Base crosscompiler link
    default: https://dev.mcst.ru/downloads/2025-05-12/cross-sp-rel-1.27.23.e2k-v5.5.10_64.tgz
  lcc_tarname:
    required: false
    description: Crosscompiler tar archive name
    default: cross-sp-rel-1.27.23.e2k-v5.5.10_64.tgz
  lcc_dirname:
    required: false
    description: Archive dirname
    default: lcc-1.27.23.e2k-v5.5.10
  qemu_e2k_static_link:
    required: false
    description: Link to qemu-user emulator
    default: https://dev.mcst.ru/downloads/2025-12-26/qemu-e2k-static
runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    # Get lcc from github actions cache or download it from mcst.dev and save to cache
    - name: Cache lcc crosscompiler
      id: cache-lcc
      uses: actions/cache@v5
      env:
        cache-name: cache-lcc
      with:
        path: /opt/mcst
        key: ${{ env.cache-name }}-${{ inputs.lcc_dirname }}

    - if: ${{ steps.cache-lcc.outputs.cache-hit != 'true' }}
      name: Install lcc
      continue-on-error: false
      shell: bash
      run: |
          wget -q ${{ inputs.lcc_link }}
          tar -xzf ${{ inputs.lcc_tarname }} -C /tmp
          mv /tmp/opt/mcst /opt
          rm -r ${{ inputs.lcc_tarname }} /tmp/opt

    # Get qemu-e2k-static from github actions cache or download from mcst.dev and save to cache
    - name: Cache qemu-e2k-static
      id: cache-qemu-e2k-static
      uses: actions/cache@v5
      env:
        cache-name: cache-qemu-e2k-static
      with:
        path: |
          /usr/local/bin/qemu-e2k-static
        key: ${{ env.cache-name }}

    - if: ${{ steps.cache-qemu-e2k-static.outputs.cache-hit != 'true' }}
      name: Install qemu-e2k-static
      continue-on-error: false
      shell: bash
      run: |
        wget -q ${{ inputs.qemu_e2k_static_link }}
        chmod +x qemu-e2k-static
        mv qemu-e2k-static /usr/local/bin

    # Add symlinks to lcc
    - name: Add lcc bin dir to PATH
      shell: bash
      run: |
        ln -sf /opt/mcst/${{ inputs.lcc_dirname }}/bin/lcc /usr/local/bin/lcc
        ln -sf /opt/mcst/${{ inputs.lcc_dirname }}/bin/l++ /usr/local/bin/l++
    
    # Add short wrapper to qemu-e2k-static
    - name: Create e2k script
      shell: bash
      run: |
        echo "#!" > /usr/local/bin/e2k
        echo "qemu-e2k-static -L /opt/mcst/${{ inputs.lcc_dirname }}/fs -- \"\$@\"" >> /usr/local/bin/e2k
        chmod +x /usr/local/bin/e2k
