---
# vim:set sw=2 ts=8 et fileencoding=utf8:
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2026 Сергей Леонтьев (leo@sai.msu.ru)

name: Tests `lcc-env-action`

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["restore-save"]  # TODO
  pull_request:
    branches: ["restore-save"]  # TODO

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v6

      - name: Test action
        uses: ./

      - name: Test install lcc
        run: |
          lcc -DTEST_DEFINITIONS tests/hello.c -o hello.elf

      - name: Test install l++
        run: |
          l++ -DTEST_DEFINITIONS tests/hello++.cpp -o hello++.elf

      - name: Test install e2k
        run: |
          e2k hello.elf
          e2k hello++.elf
