---
# vim:set sw=2 ts=8 et fileencoding=utf8:
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2026 Сергей Леонтьев (leo@sai.msu.ru)

name: Tests `lcc-env-action`

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, ubuntu-latest, ubuntu-slim]
        lcc_version: [1.27.23, 1.29.12, 1.29.16]
        qemu_e2k_version: ["1.0", "1.1"]
        exclude:
          - os: ${{ case(contains(vars.DISABLE, 'ubuntu-22.04'), 'ubuntu-22.04',
              'enable-os1') }}
          - os: ${{ case(contains(vars.DISABLE, 'ubuntu-slim'), 'ubuntu-slim',
              'enable-os2') }}
          - lcc_version: ${{ case(contains(vars.DISABLE, '1.27.23'), '1.27.23',
              'enable-lcc1') }}
          - lcc_version: ${{ case(contains(vars.DISABLE, '1.29.12'), '1.29.12',
              'enable-lcc2') }}
          - lcc_version: ${{ case(contains(vars.DISABLE, '1.29.16'), '1.29.16',
              'enable-lcc3') }}
          - qemu_e2k_version: ${{ case(contains(vars.DISABLE, '1.0'), '1.0',
              'enable-e2k1') }}
          - qemu_e2k_version: ${{ case(contains(vars.DISABLE, '1.1'), '1.1',
              'enable-e2k2') }}

    steps:
      - uses: actions/checkout@v6

      - name: Test action
        uses: ./
        with:
          lcc_version: ${{ matrix.lcc_version }}
          qemu_e2k_version: ${{ matrix.qemu_e2k_version }}

      - name: Test install lcc
        run: |
          lcc -DTEST_DEFINITIONS tests/hello.c -o hello.elf
          lcc tests/simple_false.c -o simple_false.elf

      - name: Test install l++
        run: |
          l++ -DTEST_DEFINITIONS tests/hello++.cpp -o hello++.elf

      - name: Test install e2k
        run: |
          e2k hello.elf
          e2k hello++.elf
          if e2k simple_false.elf ; then
            echo "simple_false.elf: must have non zero exit code" 1>&2
            false
          else
            true
          fi
